package GPH;

use strict;
use warnings FATAL => 'all';

our $VERSION = '1.4.1';

1;

__END__

=head1 NAME

GPH - Gitlab Perl Helpers

=head1 DESCRIPTION

set of modules and integration scripts to support building code owner specific ci jobs for gitlab

=head1 MODULES

=over 4

=item L<GPH::Composer>

parses and matches paths with a L<Composer|https://getcomposer.org/> classmap

=item L<GPH::Gitlab>

parse and process gitlab's CODEOWNER file

=item L<GPH::Infection>

parse output generated by L<infection|https://infection.github.io/> and return alternate exit code
when both msi and covered msi meet the configured threshold, but there are escaped mutants.

=item L<GPH::PHPMD>

generate custom configuration file for L<PHP Mess Detector|https://phpmd.org/>

=item L<GPH::PHPStan>

generate custom configuration file for L<PHPStan|https://phpstan.org/>

=item L<GPH::PHPUnit>

parses L<PHPUnit|https://phpunit.de/> coverage output and filters it for given code owner.
Provides option to fail if coverage is below required threshold

=item L<GPH::Psalm>

generate custom configuration file for L<Psalm|https://psalm.dev/>

=back

=head1 VERSION

1.4.1

=head1 AUTHOR

the Gitlab Perl Helpers were written by wicliff wolda <wicliff.wolda@gmail.com>

=head1 COPYRIGHT AND LICENSE

this library is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=cut
