name: "continuous integration"

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  unit-tests:
    name: "unit tests"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        perl-version:
          - '5.36'
          - '5.34'
          - '5.32'
          - '5.30'
          - '5.28'
          - '5.26'
          - '5.24'
          - '5.22'
          - '5.20'
          - '5.18'
          - '5.16'
        include:
          - name: ' (all)'
            os: ubuntu-latest
            perl-version: '5.38'
            cover: true

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - name: checkout
        uses: "actions/checkout@v4"

      - name: perl version
        run: perl -V

      - name: install dependencies
        run: cpanm --notest --installdeps --verbose .

      - if: ${{ matrix.cover }}
        run: cpanm -n Devel::Cover::Report::Coveralls Module::Build Devel::Cover Devel::Cover::Report::Codecov

      - name: build
        run: |
          perl Makefile.PL
          make

      - if: ${{ matrix.cover }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          cover -report Coveralls -test
          cover -report codecov

      - if: ${{ matrix.cover }}
        name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: wickedOne/gitlab-perl-helpers

      - if: ${{ !matrix.cover }}
        run: prove -wlvmbr t

